table fato_pedido
	lineageTag: 8f84a416-4fbc-4af6-97ce-9c080cb42c7a

	column pedido_id
		dataType: string
		lineageTag: 0eaea113-da3a-4a47-88cf-19914e06fca6
		summarizeBy: none
		sourceColumn: pedido_id

		annotation SummarizationSetBy = Automatic

	column cliente_id
		dataType: string
		lineageTag: 0cef7d6e-3ee1-4130-aad7-b48088176556
		summarizeBy: none
		sourceColumn: cliente_id

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 807bbcd8-5032-4f09-81bc-35e60e0f8292
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column data_compra
		dataType: dateTime
		formatString: Long Date
		lineageTag: 133bd758-db7a-4eff-ba89-a7a66323efcf
		summarizeBy: none
		sourceColumn: data_compra

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_aprovacao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9be70254-8ead-4f0f-af69-581dcbcf9f1f
		summarizeBy: none
		sourceColumn: data_aprovacao

		variation Variation
			isDefault
			relationship: 2ae294e4-6b28-4821-8b8c-c9333839bc70
			defaultHierarchy: LocalDateTable_c1044bf3-22e5-446d-b209-5b104cf431ea.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_envio
		dataType: dateTime
		formatString: Long Date
		lineageTag: e5b0accc-1e39-46a6-b7c5-567017f0d20f
		summarizeBy: none
		sourceColumn: data_envio

		variation Variation
			isDefault
			relationship: 34c389f7-3b26-44bf-91aa-4b582bba8fb3
			defaultHierarchy: LocalDateTable_33020959-5bd2-4eb1-890b-7e2ede7bce5f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_entrega
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7c4c7e7d-b6a7-417e-aad6-1b178ffbfb3c
		summarizeBy: none
		sourceColumn: data_entrega

		variation Variation
			isDefault
			relationship: c14f6aea-d581-4308-920c-ebe2d2341a86
			defaultHierarchy: LocalDateTable_548c90d8-5e5c-418d-946f-ddb9488598bf.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_entrega_estimada
		dataType: dateTime
		formatString: Long Date
		lineageTag: 41facd7a-362c-4fbe-9b13-925320fce353
		summarizeBy: none
		sourceColumn: data_entrega_estimada

		variation Variation
			isDefault
			relationship: ff101d8f-dd21-4f4f-a5f1-6eac10cbdd04
			defaultHierarchy: LocalDateTable_012e7c8c-4f66-4d45-85c6-938486c13b97.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ciclo_operacional_dias
		dataType: int64
		formatString: 0
		lineageTag: a8bfbf4a-303e-4001-bd12-798a86aa3add
		summarizeBy: sum
		sourceColumn: ciclo_operacional_dias

		annotation SummarizationSetBy = Automatic

	column tempo_ate_envio_dias
		dataType: int64
		formatString: 0
		lineageTag: d9ba131d-1705-4678-87b2-4f49ac02447d
		summarizeBy: sum
		sourceColumn: tempo_ate_envio_dias

		annotation SummarizationSetBy = Automatic

	column tempo_envio_entrega_dias
		dataType: int64
		formatString: 0
		lineageTag: 2460a684-ad64-46d3-887d-01b66cc616fc
		summarizeBy: sum
		sourceColumn: tempo_envio_entrega_dias

		annotation SummarizationSetBy = Automatic

	column dias_atraso
		dataType: int64
		formatString: 0
		lineageTag: ae13328d-c806-4f58-8bcd-2efde98179fa
		summarizeBy: sum
		sourceColumn: dias_atraso

		annotation SummarizationSetBy = Automatic

	column entrega_atrasada
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ee8f3341-954f-43f3-9168-2dd7a8f26268
		summarizeBy: none
		sourceColumn: entrega_atrasada

		annotation SummarizationSetBy = Automatic

	column 'Faixa Ciclo' =
			
			SWITCH (
			    TRUE(),
			    'fato_pedido'[ciclo_operacional_dias] <= 6, "Até 6",
			    'fato_pedido'[ciclo_operacional_dias] <= 9, "7–9",
			    'fato_pedido'[ciclo_operacional_dias] <= 14, "10–14",
			    'fato_pedido'[ciclo_operacional_dias] <= 19, "15–19",
			    'fato_pedido'[ciclo_operacional_dias] >= 20, "20+",
			    BLANK()
			)
		lineageTag: b57da0a6-1119-4faf-9573-ddb06fe8dd62
		summarizeBy: none
		sortByColumn: 'Ordem Faixa Ciclo'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Ordem Faixa Ciclo' =
			
			SWITCH (
			    TRUE(),
			    fato_pedido[ciclo_operacional_dias] <= 6, 1,
			    fato_pedido[ciclo_operacional_dias] <= 9, 2,
			    fato_pedido[ciclo_operacional_dias] <= 14, 3,
			    fato_pedido[ciclo_operacional_dias] <= 19, 4,
			    fato_pedido[ciclo_operacional_dias] >= 20, 5,
			    BLANK()
			)
		formatString: 0
		lineageTag: 84834b22-3bb6-451d-b5eb-96553051326c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Faixa Atraso' =
			
			SWITCH (
			    TRUE(),
			    fato_pedido[dias_atraso] <= 0, "Sem Atraso",
			    fato_pedido[dias_atraso] <= 3, "Até 3 dias",
			    fato_pedido[dias_atraso] <= 7, "4–7 dias",
			    fato_pedido[dias_atraso] <= 14, "8–14 dias",
			    fato_pedido[dias_atraso] <= 30, "15–30 dias",
			    fato_pedido[dias_atraso] > 30,  "Mais de 30 dias",
			
			    BLANK()
			)
		lineageTag: 7fcad9dd-c0f1-4147-b86d-672831697271
		summarizeBy: none
		sortByColumn: 'Ordem Faixa Atraso'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Ordem Faixa Atraso' =
			
			SWITCH (
			    TRUE(),
			    fato_pedido[dias_atraso] <= 0, 1,
			    fato_pedido[dias_atraso] <= 3, 2,
			    fato_pedido[dias_atraso] <= 7, 3,
			    fato_pedido[dias_atraso] <= 14, 4,
			    fato_pedido[dias_atraso] <= 30, 5,
			    fato_pedido[dias_atraso] > 30,  6,
			    BLANK()
			)
		formatString: 0
		lineageTag: 7320fe77-0048-4c30-b208-b39ed22d6bad
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Status Entrega' =
			
			IF(
			    fato_pedido[dias_atraso] > 0,
			    "Em atraso",
			    "No prazo"
			)
		lineageTag: a5695e99-0e39-429e-8998-3915b8f60c30
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fato_pedido = m
		mode: import
		source =
				let
				  Origem = PostgreSQL.Database("localhost:5432", "nexus"),
				  #"Navegação 1" = Origem{[Schema = "dw", Item = "fato_pedido"]}[Data],
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Navegação 1", "status_entrega", each if [entrega_atrasada] = false then "Sem atraso" else if [entrega_atrasada] = true then "Com atraso" else null),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna Condicional Adicionada",{"status_entrega"})
				in
				  #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

